# URL: http://localhost:3000/auth/register
# Method: POST
# Headers: 
#   Content-Type: application/json
# Body:
# {
#   "email": "test@example.com",
#   "password": "password123",
#   "nickname": "테스트"
# }

POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "test6@test.com",
  "password": "123123",
  "nickname": "개똥이"
}