import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { LayoutStyle } from "./layout.css";
import { AuthProvider } from "./contexts/AuthContext";
import "@/app/styles/global.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    google: "notranslate",
    robots: "noindex,nofollow",
  },
  // HTTP 등가 메타 태그
  metadataBase: new URL("https://yourwebsite.com"),
  viewport: "width=device-width, initial-scale=1.0",
  themeColor: "#ffffff",
  // 캐시 컨트롤 관련 설정
  applicationName: "Next.js App",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${LayoutStyle}`}
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
